const ACTIONS = {
    SHOW_ERR_MESSAGE: 'SHOW_ERR_MESSAGE',
    SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    GET_PRODUCTS: 'GET_PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    GET_PRODUCT: 'GET_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    ADD_CART: "ADD_CART",
    REMOVE_CART: 'REMOVE_CART',
    EMPTY_CART:'EMPTY_CART'

}

export default ACTIONS